<div class="main-bg" id="service-main-bg">
	<div id="page-banner">	
	</div>
	<div id="main01">
		<div class="slogan">您的想法，我們來實現</div>
		
		<div id="page-wrap">

			<!-- breadcrumbs -->
			<?php echo $this->getChildHtml('breadcrumbs') ?>
			
			<div id="page-content">
				<h1 class="page-title">服務項目</h1>
				<img src="<?php echo $this->getSkinUrl('tinyapple/images/icon01.png') ?>" alt="" class="icon" width="43px">
				<div class="services-content">
					<ul class="services-list">
						<li>房屋增建修繕</li>
						<li>浴室整修</li>
						<li>外牆拉皮</li>
						<li>拋光石英磚工程</li>
						<li>切磚、打底工程</li>
						<li>空心磚、花磚、植草磚施工</li>
						<li>套房規劃修改</li>
						<li>H鋼構增建</li>
						<li>外牆、陽台、防水</li>
						<li>押送、灌漿工程</li>
						<li>地層下陷整修</li>
						<li>擋土牆、廢土、回填工程</li>
						<li>系統櫃設計與製作</li>
					</ul>
					<div class="services-pics clearfix">
						<img src="<?php echo $this->getSkinUrl('tinyapple/images/service/service-pic01.jpg') ?>" alt="">
						<img src="<?php echo $this->getSkinUrl('tinyapple/images/service/service-pic02.jpg') ?>" alt="">
						<img src="<?php echo $this->getSkinUrl('tinyapple/images/service/service-pic03.jpg') ?>" alt="">
					</div><!-- end of services-pics -->
				</div><!-- end of services-content -->
			</div><!-- end of page-content -->
		</div><!--end of page-wrap -->
	</div><!-- end of main01 -->
</div><!-- end of main-bg -->