<div class="main-bg" id="contact-main-bg">
	<div id="page-banner">
	</div>
	<div id="main01">
		<div class="slogan">免費到府估價！歡迎聯絡！</div>
		
		<div id="page-wrap">

			<!-- breadcrumbs -->
			<?php echo $this->getChildHtml('breadcrumbs') ?>
			
			<div id="page-content">
				<h1 class="page-title">聯絡我們</h1>
				<img src="<?php echo $this->getSkinUrl('tinyapple/images/icon01.png') ?>" alt="" class="icon" width="43px">
				<div class="contact-content">
					<div class="contact-ad">
						<div class="contact-ad-context">
							<p>負責台中、彰化、南投</p>
							<p>免費到府估價．歡迎聯絡我們</p>
							<p>許先生<a href="tel:0909-218810" class="dial">0909-218810</a></p>	
						</div>
					</div>
					<ul class="contact-info">
						<li>
							<span><img src="<?php echo $this->getSkinUrl('tinyapple/images/icon-people.png') ?>" alt="" width="25px"></span>
							<span>許先生</span></li>
						<li>
							<span><img src="<?php echo $this->getSkinUrl('tinyapple/images/icon-phone.png') ?>" alt="" width="25px"></span>
							<span><a href="tel:0909-218810" class="dial">0909-218810</a></span></li>
						<li>
							<span><img src="<?php echo $this->getSkinUrl('tinyapple/images/icon-email.png') ?>" alt="" width="25px"></span>
							<span><a href="mailto:1223son@gmail.com">1223son@gmail.com</a></span></li>
						<li>
							<span><img src="<?php echo $this->getSkinUrl('tinyapple/images/icon-locate.png') ?>" alt="" width="25px"></span>
							<span>台中市烏日區五光路五中巷12之1號</span></li>
					</ul>
				</div>
			</div><!-- end of page-content -->
		</div><!--end of page-wrap -->
	</div><!-- end of main01 -->
</div><!-- end of main-bg -->