<?php $typeValueToFilter = $this->helper('homepage/data')
    ->getOptionValueIdFromAttributeOptionLabel('attributeName', 'type', '完工作品') ?>

<?php $productCollection = Mage::getModel('catalog/product')->getCollection()
    ->addFieldToFilter('type', $typeValueToFilter)
    ->setOrder('entity_id', 'DESC') ?>

<h2>completed</h2>

<?php foreach ($productCollection as $product): ?>
    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
    <div>
        <a href="<?php echo $this->helper('works/data')->getWorksUrl($_product) ?>">
            <?php echo $_product->getName() ?>
        </a>
        <?php echo $_product->getId() ?>
        <br />
        <?php echo $_product->getName() ?>
    </div>
<?php endforeach ?>
