<?php $productCollection = $this->getCompletedProducts('完工作品') ?>



<?php echo $this->getChildHtml('breadcrumbs') ?>

<h2>completed</h2>

<?php foreach ($productCollection as $product): ?>
    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
    <div>
        <div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" /></div>
        <a href="<?php echo $this->helper('works/data')->getWorksUrl($_product) ?>">
            <?php echo $_product->getName() ?>
        </a>
        <?php echo $_product->getId() ?>
    </div>
    <br />
<?php endforeach ?>
