<?php $_product = $this->getProduct() ?>
<?php $mediaGallery = $_product->getMediaGalleryImages() ?>
<?php $block = $this->getLayout()->createBlock('works/content'); ?>


<div class="main02-bg">
    <div id="page-banner" class="for-v-middle">
        <div class="page-title-wrap">
            <h1 class="page-title">
                <?php echo $this->getWorkPageTitle() ?>
            </h1>
            <h2><?php echo $_product->getName() ?></h2>
        </div>
    </div>
    <div id="main01">
        <div id="page-wrap">
            <!-- breadcrumbs -->
            <?php echo $this->getChildHtml('breadcrumbs') ?>

            <div id="page-content">
                <?php echo $this->getChildHtml('aside') ?>
                <div id="page-main">

                    <div id="products_show_pic" class="slider">
                        <div class="p-title for-v-middle"><?php echo $_product->getName() ?></div>
                        <div id="slider" class="flexslider flexslider_pic">
                            <ul class="slides">
                                <?php $count = 0; ?>
                                <?php foreach ($mediaGallery as $_media): ?>
                                    <?php $count++ ?>
                                    <?php if (strpos($_media->getLabel(), '完工作品') !== false || $count == count($mediaGallery)): ?>
                                        <?php $count-- ?>
                                        <li>
                                            <a href="<?php echo $_media->getUrl() ?>"  data-gall="gall1"  class="md-trigger venobox vbox-item" data-modal="materialsTitle1">
                                            <img src="<?php echo $this->helper('timage')
                                                ->init($_media->getUrl())
                                                ->keepAspectRatio(true)
                                                ->resize(674, 500) ?>" />
                                            </a>
                                        </li>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                        </div><!-- end of slider -->
                        <div id="carousel" class="flexslider flexslider_pic clearfix">
                            <ul class="slides picS">
                                <?php $count = 0; ?>
                                <?php foreach ($mediaGallery as $_media): ?>
                                    <?php $count++ ?>
                                    <?php if (strpos($_media->getLabel(), '完工作品') !== false || $count == count($mediaGallery)): ?>
                                        <?php $count-- ?>
                                        <li><img src="<?php
                                            echo $this->helper('timage')
                                                ->init($_media->getUrl())
                                                ->keepAspectRatio(true)
                                                ->resize(674, 500) ?>" /></li>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                        </div><!-- end of carousel -->

                        <div id="p-controls-btn">
                            <?php if (!$this->isFirstProduct('完工作品', $_product->getId())): ?>
                                <a href="<?php echo $this->getPrevCompletedProductId('完工作品', $_product->getId()) ?>" class="p-c-btn btn-prev">上件作品</a>
                            <?php endif ?>
                            <?php if (!$this->isLastProduct('完工作品', $_product->getId())): ?>
                                <a href="<?php echo $this->getNextCompletedProductId('完工作品', $_product->getId()) ?>" class="p-c-btn btn-next">下件作品</a>
                            <?php endif ?>
                            <a href="<?php echo Mage::helper('homepage/data')->getControllerUrl() . 'index/category_id/' . $block->getCategoryId() ?>" class="p-c-btn btn-back">回列表</a>
                        </div><!-- end of p-controls-btn -->
                    </div><!-- end of products_show_pic -->

                    <div id="products_show_introduction">
                        <div class="title">作品介紹</div>
                        <?php foreach ($mediaGallery as $_media): ?>
                            <figure>
                                <p><?php echo $_media->getLabel() ?></p>
                                <img src="<?php echo $this->helper('timage')->init($_media->getUrl())->keepFrame(false)->resize(580, null) ?>" />
                            </figure>
                        <?php endforeach ?>
                    </div><!-- end of products_show_introduction -->

                </div>

            </div><!-- end of page-content -->
        </div><!--end of page-wrap -->
    </div><!-- end of main01 -->
</div><!-- end of main-bg -->


<script type="text/javascript">
/*
     jQuery(document).ready(function(){
     jQuery('#carousel').flexslider({
     animation: "slide",
     controlNav: false,
     animationLoop: false,
     slideshow: false,
     itemWidth: 82,
     itemMargin: 4,
     asNavFor: '#slider'
     });

     jQuery('#slider').flexslider({
     animation: "slide",
     controlNav: false,
     animationLoop: false,
     slideshow: false,
     sync: "#carousel"
     });
     });
 */

</script>