<?php $mediaGallery = $this->getProduct()->getMediaGalleryImages() ?>



    <div class="main02-bg">
    <div id="page-banner" class="for-v-middle">
        <h1 class="page-title"><?php echo $this->getWorkPageTitle() ?></h1>
    </div>
    <div id="main01">
        <div id="page-wrap">
            <!-- breadcrumbs -->
            <?php echo $this->getChildHtml('breadcrumbs') ?>

            <div id="page-content">
                <?php echo $this->getChildHtml('aside') ?>

                <div id="page-main">
                    <div class="title">浴室整修 - 作業流程</div>

                    <?php foreach ($mediaGallery as $_media): ?>
                        <figure>
                            <p><span><?php echo $_media->getPosition() ?> <spna> - </span> </span><?php echo $_media->getLabel() ?>
                            </p>
                            <img src="<?php echo $this->helper('timage')->init($_media->getUrl())->keepFrame(false)->resize(580, null) ?>">
                        </figure>
                    <?php endforeach ?>

                </div> <!-- end of page-main -->

            </div><!-- end of page-content -->
        </div><!--end of page-wrap -->
    </div><!-- end of main01 -->
</div><!-- end of main-bg -->


