<?php $categoryCollection = Mage::getModel('catalog/category')->getCollection() ?>
<?php foreach ($categoryCollection as $category): ?>
    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
    <div>
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" />
    </div>
<?php endforeach ?>





<h2>works content</h2>

<?php foreach ($productCollection as $product): ?>
    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
    <div>
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" />
    </div>
<?php endforeach ?>
