<?php $categoryCollection = $this->getCategoryCollection() ?>

<div class="main02-bg">
    <div id="page-banner" class="for-v-middle">
        <h1 class="page-title"><?php echo $this->getWorkPageTitle() ?></h1>
    </div>
    <div id="main01">
        <div id="page-wrap">
            <!-- breadcrumbs -->
            <?php echo $this->getChildHtml('breadcrumbs') ?>

            <div id="page-content">
                <?php echo $this->getChildHtml('aside') ?>

                <div id="page-main">

                    <div class="works-list">

                        <?php foreach ($categoryCollection as $category): ?>
                            <div class="work-item clearfix">
                                <?php if ($category->getImage()): ?>
                                    <div class="pic">
                                        <img src="<?php echo $this->helper('timage')
                                            ->init($category->getImageUrl())
                                            ->setWidth(375)
                                            ->setHeight(308)
                                            ->crop()
                                            ->resize() ?>" alt="" />
                                    </div>
                                <?php endif ?>
                                <div class="work-item-right">
                                    <div class="title"><?php echo $category->getName() ?></div>
                                    <div class="btns">
                                        <?php $product = $this->getFlowProduct('作業流程', $category->getName()) ?>
                                        <?php if ($product->getId()): ?>
                                            <a class="more-btn" href="<?php echo $this->helper('homepage/data')->getRouterUrl() ?>flow/index/id/<?php echo $product->getId() ?>">作業流程</a>
                                        <?php endif ?>
                                        <a class="more-btn" href="<?php echo $this->helper('homepage/data')->getRouterUrl() ?>completed/index/category_id/<?php echo $category->getId() ?>">完工作品</a>
                                    </div>
                                </div>
                            </div><!-- end of work-item -->
                        <?php endforeach ?>

                    </div><!-- end of works-list -->
                </div>

            </div><!-- end of page-content -->
        </div><!--end of page-wrap -->
    </div><!-- end of main01 -->
</div><!-- end of main-bg -->



