<?php $categoryCollection = Mage::getModel('catalog/category')->getCollection()
    ->addAttributeToSelect('*')
    ->addFieldToFilter('level', 2) ?>

<?php echo $this->getChildHtml('breadcrumbs') ?>

<?php foreach ($categoryCollection as $category): ?>
    <div>
        <?php echo $category->getName() ?>

        <?php if ($category->getImage()): ?>
            <img src="<?php echo $this->getResizedImage('category', $category->getImage(), 416) ?>" />
        <?php endif ?>

        <a href="<?php echo $this->helper('homepage/data')->getRouterUrl() ?>flow">作業流程</a>
        <a href="<?php echo $this->helper('homepage/data')->getRouterUrl() ?>completed">完工作品</a>
        <?php // Zend_Debug::dump($category->getData()) ?>
    </div>
    <br />
<?php endforeach ?>





