
<footer>

    <!-- star.btnPageTop-->
    <div class="pagetopbtn" id="PageTopBtn"><img src="<?php echo $this->getSkinUrl('tinyapple/images/btnPageTop.png') ?>" class="animate"></div>
    <!--end.btnPageTop-->

    <div class="container clearfix">
        <div id="footer-logo" class="clearfix">
            <a href="<?php echo Mage::getBaseUrl() ?>" class="left for-v-middle"><img src="<?php echo $this->getSkinUrl('tinyapple/images/footer-logo.png') ?>" alt=""></a>
        </div><!-- end of footer-contact-info -->

        <div id="footer-ad" class="ad-block">
            <a href="tel:0909-218810" class="dial askprice"><span><b>免費到府</b>估價</span></a>
            <a href="tel:0909-218810" class="dial phone-no">0909-218810<span>許先生</span></a>
            <p>
                <span class="social-link"><a href="https://www.facebook.com/groups/1726826227534038/?fref=ts" target="_blank" class="fb-icon"><span class="fa fa-facebook"></span>加入我們！</a></span>
                <span class="social-link footer-lineid">Line ID: <a href="http://line.naver.jp/ti/p/~Son711223" target="_blank">son711223</a></span>
                <span>E-mail: <a href="mailto:1223son@gmail.com">1223son@gmail.com</a></span>
            </p>
        </div>

        <div id="footer-nav">
            <ul>
                <li class="mainShow"><a href="<?php echo Mage::getBaseUrl() ?>aboutus">公司簡介<span>About</span></a></li><!-- (sol. for the space of inline-block)
                --><li class="mainShow"><a href="<?php echo Mage::getBaseUrl() ?>services">服務項目<span>Service</span></a></li><!-- (sol. for the space of inline-block)
                --><li class="mainShow"><a href="<?php echo Mage::getBaseUrl() ?>works">作品展示<span>Works</span></a></li><!-- (sol. for the space of inline-block)
                --><li class="mainShow"><a href="<?php echo Mage::getBaseUrl() ?>contact">聯絡我們<span>Contact Us</span></a></li><!-- (sol. for the space of inline-block)
                --><li class="mainShow"><a href="<?php echo Mage::getBaseUrl() ?>"><span class="fa fa-home"></span><span>Home</span></a></li>
            </ul>
        </div><!-- end of footer-contact-info -->

        <div id="copyright">
            <p>Copyright&copy; 2016 小蘋果工程 All Rights Reserved.</p>
            <p class="address">台中市烏日區五光路五中巷12之1號</p>
        </div>
        <!-- end of copyright -->
    </div><!-- end of container -->

</footer>
<!-- footer end -->