
<footer>

    <!-- star.btnPageTop-->
    <div class="pagetopbtn" id="PageTopBtn"><img src="<?php echo $this->getSkinUrl('tinyapple/images/btnPageTop.png') ?>" class="animate"></div>
    <!--end.btnPageTop-->

    <div class="container clearfix">
        <div id="footer-logo" class="clearfix">
            <a href="index.html" class="left for-v-middle"><img src="<?php echo $this->getSkinUrl('tinyapple/images/footer-logo.png') ?>" alt=""></a>
        </div><!-- end of footer-contact-info -->

        <div id="footer-ad" class="ad-block">
            <a href="tel:0909-218810" class="dial askprice"><span><b>免費到府</b>估價</span></a>
            <a href="tel:0909-218810" class="dial phone-no">0909-218810<span>許先生</span></a>
            <p>E-mail: <a href="mailto:1223son@gmail.com">1223son@gmail.com</a></p>
        </div>

        <div id="footer-nav">
            <ul>
                <li class="mainShow"><a href="aboutus.html">公司簡介<span>About</span></a></li>
                <li class="mainShow"><a href="services.html">服務項目<span>Service</span></a></li>
                <li class="mainShow"><a href="products.html">作品展示<span>Works</span></a></li>
                <li class="mainShow"><a href="contact.html">聯絡我們<span>Contact Us</span></a></li>
                <li class="mainShow"><a href="index.html"><span class="fa fa-home"></span><span>Home</span></a></li>
            </ul>
        </div><!-- end of footer-contact-info -->

        <div id="copyright">
            <p>Copyright&copy; 2016 小蘋果工程 All Rights Reserved.</p>
            <p class="address">台中市烏日區五光路五中巷12之1號</p>
        </div>
        <!-- end of copyright -->
    </div><!-- end of container -->

</footer>
<!-- footer end -->