<header>
    <div class="container clearfix">
        <div class="collapse-button animate">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </div>

        <a href="<?php echo Mage::getBaseUrl() ?>" id="logo" class="left for-v-middle"><img src="<?php echo $this->getSkinUrl('tinyapple/images/logo.png') ?>" alt="logo圖"></a>

        <div id="header-ad" class="right ad-block">
            <a href="tel:0909-218810" class="dial askprice"><span><b>免費到府</b>估價</span></a>
            <a href="tel:0909-218810" class="dial phone-no">0909-218810<span>許先生</span></a>
        </div>

        <nav id="main-nav" class="right animate">
            <ul class="clearfix">
                <li class="mainShow <?php echo $this->getMenuClass('about') ?>"><a href="<?php echo Mage::getBaseUrl() ?>aboutus">公司簡介<span>About</span></a></li>
                <li class="mainShow <?php echo $this->getMenuClass('service') ?>"><a href="<?php echo Mage::getBaseUrl() ?>services">服務項目<span>Service</span></a></li>
                <li class="mainShow <?php echo $this->getMenuClass('works') ?>"><a href="<?php echo Mage::getBaseUrl() ?>works">作品展示<span>Works</span></a></li>
                <li class="mainShow <?php echo $this->getMenuClass('contact') ?>"><a href="<?php echo Mage::getBaseUrl() ?>contact">聯絡我們<span>Contact Us</span></a></li>
                <li class="mainShow <?php echo $this->getMenuClass('cms') ?>"><a href="<?php echo Mage::getBaseUrl() ?>"><span class="fa fa-home"></span><span>Home</span></a></li>
            </ul>
        </nav><!-- end of main-nav -->

    </div><!-- end of container -->

</header>
<!-- header end -->
