
<div id="content">
    <div id="idx-banner" class="clearfix">
        <div class="idx-banner-overlay-l">x</div>
        <div class="idx-banner-overlay-r">x</div>
        <div id="idx-bn-slide" class="slider clearfix">
            <div>
                <img src="<?php echo $this->getSkinUrl('tinyapple/images/idx-banner/idx-banner03.jpg') ?>" alt="">
                <div class="bn-text for-v-middle">
                    <div>
                        <div class="slogan">台中 / 彰化 / 南投<br>公寓、透天厝、浴室裝修</div>
                        <a href="<?php echo $this->getUrl('works/completed/index', array('category_id' => 5)) ?>" class="more-btn">公寓整修</a>
                    </div>
                </div>
            </div>
            <div>
                <img src="<?php echo $this->getSkinUrl('tinyapple/images/idx-banner/idx-banner02.jpg') ?>" alt="">
                <div class="bn-text for-v-middle">
                    <div>
                        <div class="slogan">台中 / 彰化 / 南投<br>公寓、透天厝、浴室裝修</div>
                        <a href="<?php echo $this->getUrl('works/completed/index', array('category_id' => 4)) ?>" class="more-btn">浴室裝修</a>
                    </div>
                </div>
            </div>
            <div>
                <img src="<?php echo $this->getSkinUrl('tinyapple/images/idx-banner/idx-banner01.jpg') ?>" alt="">
                <div class="bn-text for-v-middle">
                    <div>
                        <div class="slogan">台中 / 彰化 / 南投<br>公寓、透天厝、浴室裝修</div>
                        <a href="<?php echo $this->getUrl('works/completed/index', array('category_id' => 4)) ?>" class="more-btn">浴室裝修</a>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- end of idx-banner -->


    <div id="idx-content">

        <div id="idx-top-section" class="clearfix">

            <div class="container">
                <div class="idx-about">
                    <h1 class="title">小蘋果工程</h1>
                    <div class="idx-company-pic"><img src="<?php echo $this->getSkinUrl('tinyapple/images/company-pic.jpg') ?>" alt=""></div>
                    <div class="idx-desc">
                        <p>用心傾聽客戶的需求，秉持著誠心、真心、用心的服務精神本公司擁有最專業的工作團隊為客戶嚴格把關，替客戶設計一個舒適且符合客戶需求的生活空間!</p>
                        <img src="<?php echo $this->getSkinUrl('tinyapple/images/icon01.png') ?>" alt="" width="30px" class="icon">
                        <p class="em-p blue-word">專門負責台中 / 彰化 / 南投 ， 浴室整修、透天厝、公寓整修工程。</p>
                        <a href="<?php echo Mage::getBaseUrl() ?>aboutus" class="more-btn">更多內容</a>
                    </div>
                </div><!-- (sol. for the space of inline-block)
						end of idx-about --><div class="idx-service">
                    <div class="title">服務項目</div>
                    <table>
                        <tr>
                            <td class="align-right">
                                套房規劃修改<br>浴室整修<br>天花板裝潢
                            </td>
                            <td>
                                <img src="<?php echo $this->getSkinUrl('tinyapple/images/idx-pic01.jpg') ?>" alt="">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <img src="<?php echo $this->getSkinUrl('tinyapple/images/idx-pic02.jpg') ?>" alt="">
                            </td>
                            <td class="align-left">
                                <p>土木工程<br>水電工程<br>油漆工程</p>
                                <a href="<?php echo Mage::getBaseUrl() ?>services" class="more-btn">更多服務</a>
                            </td>
                        </tr>
                    </table>
                </div>
                <!-- end of idx-service -->
            </div>
            <!-- end of container -->

        </div><!-- end of idx-top-section -->

        <div id="idx-lower-section" class="container">

            <div class="container">
                <div class="title underline-title">最新作品</div>

                <?php echo $this->getChildHtml('new_products') ?>
            </div>
            <!-- end of container -->

        </div><!-- end of idx-lower-section -->
    </div><!-- end of idx-content -->
</div><!-- end of content -->

<script type="text/javascript">
    jQuery(document).ready(function() {
        var slick_object = {
            window_width: 0,
            init: function (target) {
                this.runMainBannerSlider(target, this.calcPartialImageWidth());
            },
            runMainBannerSlider: function (target, centerPadding) {
                jQuery(target).slick({
                    arrows: true,
                    adaptiveHeight: true,
                    autoplay: true,
                    autoplaySpeed: 6000,
                    useTransform: false,
                    dots: false,
                    infinite: true,
                    centerMode: true,
                    centerPadding: (centerPadding > 0) ? centerPadding + 'px' : 0,
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    pauseOnHover: false,
                    PauseOnFocus: false
                });
            },
            resizeMainBannerSlider: function (target, centerPadding) {
                jQuery(target).slick('slickSetOption', {centerPadding: (centerPadding > 0) ? centerPadding + 'px' : 0});
            },
            calcPartialImageWidth: function () {
                this.window_width = jQuery(window).width() + this.getScrollBarWidth();
                return ((this.window_width / 2) - (480 + this.getScrollBarWidth() / 2) > 0) ? (this.window_width / 2) - (480 + this.getScrollBarWidth() / 2) : 0;
            },
            getScrollBarWidth: function () {
                var $outer = jQuery('<div>').css({visibility: 'hidden', width: 100, overflow: 'scroll'}).appendTo('body'),
                    widthWithScroll = jQuery('<div>').css({width: '100%'}).appendTo($outer).outerWidth();
                $outer.remove();
                return 100 - widthWithScroll;
            }
        };

        slick_object.init("#idx-bn-slide");
        jQuery(window).resize(function () {
            slick_object.resizeMainBannerSlider("#idx-bn-slide", slick_object.calcPartialImageWidth());
        });

    });
</script>
